name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login gchr.io -u ${{ github.actor}} --password-stdin
      - run: docker build -t gchr.io/${{ github.repository }}:latest .
      - run: docker push gchr.io/${{ github.repository }}:latest
